# Logo
logo: css/images/logo.png # Empty this to unset logo and show site title in the same place

# Header
menu:
  主页: .
  归档: archives
  分类: categories
  标签: tags
  关于: about

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # Whether to show profile bar
gravatar: false # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: http://github.com/ppoffice/hexo-theme-icarus
  twitter: '#'
  facebook: '#'
  dribbble: '#'
  rss: atom.xml

# Links
links:
  Hexo: http://hexo.io

# CDN
# cdn: # You can choose "useso" instead of "google apis"(default).
cdn: useso
# OR
# cdn:

# Comment
comment:
    disqus_shortname: hexo-theme-hueman # enter disqus shortname here
    duoshuo_shortname: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Miscellaneous
google_site_verification:
google_analytics:
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
